-- Generated by SQLite Compare utility

-- The script can be used to migrate database
-- C:\Documents and Settings\eventgenie\Desktop\db\eventgenie_v46.db schema
-- to the schema of database
-- C:\Documents and Settings\eventgenie\Desktop\db\eventgenie_v47.db

BEGIN TRANSACTION;


-- Creating table apprefs from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_apprefs_534011718
(
    liveStatus INTEGER NULL,
    isUsingHoldingPage bit NULL,
    modifiedBy nvarchar(50) NULL,
    iconUrl nvarchar(500) NULL,
    isFeatured bit NULL,
    eventEndDate datetime NULL,
    isAvailable bit NULL,
    scheduledDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    scheduledLiveStatus INTEGER NULL,
    _id nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(300) NULL,
    createdDate datetime NULL,
    app bigint NULL,
    icon bigint NULL,
    scheduledTaskName nvarchar(500) NULL,
    eventLocation nvarchar(500) NULL,
    strapLine nvarchar(500) NULL,
    eventStartDate datetime NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    createdBy nvarchar(50) NULL,
    permissionGroup bigint NULL,
    holdingPageHTML text NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL
);

-- Copying rows from original table to the new table

INSERT INTO temp_apprefs_534011718 (liveStatus,isUsingHoldingPage,modifiedBy,iconUrl,isFeatured,eventEndDate,isAvailable,scheduledDate,id,scheduledLiveStatus,_id,importBatch,name,createdDate,app,icon,scheduledTaskName,eventLocation,strapLine,eventStartDate,importCameFrom,modifiedDate,createdBy,holdingPageHTML,importKey,_namespace,permissionGroup) SELECT liveStatus,isUsingHoldingPage,modifiedBy,iconUrl,isFeatured,eventEndDate,isAvailable,scheduledDate,id,scheduledLiveStatus,_id,importBatch,name,createdDate,app,icon,scheduledTaskName,eventLocation,strapLine,eventStartDate,importCameFrom,modifiedDate,createdBy,holdingPageHTML,importKey,_namespace,permissionGroup FROM apprefs;

-- Droping the original table and renaming the temporary table

DROP TABLE apprefs;
ALTER TABLE temp_apprefs_534011718 RENAME TO apprefs;

-- Creating table locations from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_locations_1655911537
(
    mapPosition_colour nvarchar(500) NULL,
    mapPosition_vectors nvarchar(500) NULL,
    mapPosition_zIndex int NULL,
    mapPosition_vectorsFormat int NULL,
    mapPosition_textBoundingBox text NULL,
    mapPosition_labelColour nvarchar(500) NULL,
    mapPosition_rotation int NULL,
    mapPosition_map bigint NULL,
    mapPosition_label nvarchar(500) NULL,
    mapPosition_type int NULL,
    mapPosition_version int NULL,
    mapPosition_vectorsBig text NULL,
    createdBy nvarchar(50) NULL,
    _id nvarchar(500) NULL,
    modifiedBy nvarchar(50) NULL,
    locationType nvarchar(500) NULL,
    name nvarchar(500) PRIMARY KEY ASC NOT NULL,
    importBatch nvarchar(500) NULL,
    importCameFrom nvarchar(500) NULL,
    createdDate datetime NULL,
    modifiedDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL
);

-- Copying rows from original table to the new table

INSERT INTO temp_locations_1655911537 (mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,createdBy,_id,modifiedBy,locationType,name,importBatch,importCameFrom,createdDate,modifiedDate,importKey,_namespace,mapPosition_textBoundingBox) SELECT mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,createdBy,_id,modifiedBy,locationType,name,importBatch,importCameFrom,createdDate,modifiedDate,importKey,_namespace,NULL AS mapPosition_textBoundingBox FROM locations;

-- Droping the original table and renaming the temporary table

DROP TABLE locations;
ALTER TABLE temp_locations_1655911537 RENAME TO locations;

-- Creating associated indexes from scratch

CREATE INDEX locations_i5
ON locations
(
    name
);

-- Creating table meetinglocations from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_meetinglocations_630327709
(
    mapPosition_colour nvarchar(500) NULL,
    mapPosition_vectors nvarchar(500) NULL,
    mapPosition_zIndex int NULL,
    mapPosition_vectorsFormat int NULL,
    mapPosition_textBoundingBox text NULL,
    mapPosition_labelColour nvarchar(500) NULL,
    mapPosition_rotation int NULL,
    mapPosition_map bigint NULL,
    mapPosition_label nvarchar(500) NULL,
    mapPosition_type int NULL,
    mapPosition_version int NULL,
    mapPosition_vectorsBig text NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    meetingsCapacity INTEGER NULL,
    modifiedDate datetime NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(500) PRIMARY KEY ASC NOT NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL
);

-- Copying rows from original table to the new table

INSERT INTO temp_meetinglocations_630327709 (mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,modifiedBy,importCameFrom,meetingsCapacity,modifiedDate,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,mapPosition_textBoundingBox) SELECT mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,modifiedBy,importCameFrom,meetingsCapacity,modifiedDate,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,NULL AS mapPosition_textBoundingBox FROM meetinglocations;

-- Droping the original table and renaming the temporary table

DROP TABLE meetinglocations;
ALTER TABLE temp_meetinglocations_630327709 RENAME TO meetinglocations;

COMMIT TRANSACTION;
