-- Generated by SQLite Compare utility

-- The script can be used to migrate database
-- C:\Documents and Settings\eventgenie\Desktop\db\eventgenie_v29.db schema
-- to the schema of database
-- C:\Documents and Settings\eventgenie\Desktop\db\eventgenie_v30.db

BEGIN TRANSACTION;


-- Creating table qr_codes from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_qr_codes_534011718
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type NVARCHAR(50),
    time DATETIME,
    displayname NVARCHAR(100),
    code NVARCHAR(7100),
    _namespace NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_qr_codes_534011718 (type,time,displayname,code,_namespace,id) SELECT type,time,displayname,code,_namespace,NULL AS id FROM qr_codes;

-- Droping the original table and renaming the temporary table

DROP TABLE qr_codes;
ALTER TABLE temp_qr_codes_534011718 RENAME TO qr_codes;

COMMIT TRANSACTION;
