-- Generated by SQLite Compare utility

-- The script can be used to migrate database
-- C:\temp\db_diff\eventgenie.db schema
-- to the schema of database
-- C:\temp\db_diff\eventgenie_new.db

BEGIN TRANSACTION;


CREATE TABLE activitystreamcomments
(
    liveStatus INTEGER NULL,
    scheduledTaskName nvarchar(500) NULL,
    modifiedBy nvarchar(50) NULL,
    preAbuseLiveStatus INTEGER NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    message text NULL,
    timestamp datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    scheduledDate datetime NULL,
    author_linkUrl nvarchar(500) NULL,
    author_imageUrl nvarchar(500) NULL,
    author_name nvarchar(500) NULL,
    author_exhibitor bigint NULL,
    author_visitor bigint NULL,
    scheduledLiveStatus INTEGER NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    abuseStatus nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    activityStreamPost bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamcomments_abuseReports
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamcomments_id bigint NULL,
    abuseReports bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamcomments_relatedTags
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamcomments_id bigint NULL,
    relatedTags bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts
(
    liveStatus INTEGER NULL,
    modifiedBy nvarchar(50) NULL,
    preAbuseLiveStatus INTEGER NULL,
    type nvarchar(500) NULL,
    buoyancy INTEGER NULL,
    timestamp datetime NULL,
    scheduledDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    author_linkUrl nvarchar(500) NULL,
    author_imageUrl nvarchar(500) NULL,
    author_name nvarchar(500) NULL,
    author_exhibitor bigint NULL,
    author_visitor bigint NULL,
    title nvarchar(500) NULL,
    scheduledLiveStatus INTEGER NULL,
    _id nvarchar(500) NULL,
    abuseStatus nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    scheduledTaskName nvarchar(500) NULL,
    importCameFrom nvarchar(500) NULL,
	isFavourite BOOLEAN DEFAULT 0,
    url nvarchar(500) NULL,
    modifiedDate datetime NULL,
    message text NULL,
    noComments INTEGER NULL,
    createdBy nvarchar(50) NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_abuseReports
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    abuseReports bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedDownloadables
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedDownloadables bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedExhibitors
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedExhibitors bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedPOIs
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedPOIs bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedProducts
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedProducts bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedSessions
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedSessions bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedSpeakers
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedSpeakers bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedSubSessions
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedSubSessions bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_associatedVisitors
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    associatedVisitors bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_comments
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    comments bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_images
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    images bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_imagesUrl
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    imagesUrl nvarchar(500) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE activitystreamposts_relatedTags
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    activitystreamposts_id bigint NULL,
    relatedTags bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Creating table adbanners from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_adbanners_534011718
(
    modifiedBy nvarchar(50) NULL,
    linkType INTEGER NULL,
    importCameFrom nvarchar(500) NULL,
    infoPage bigint NULL,
    iPad2BannerUrl nvarchar(500) NULL,
    modifiedDate datetime NULL,
    portalBanner bigint NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    iPadBannerUrl nvarchar(500) NULL,
    bannerUrl nvarchar(500) NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    iPad2Banner bigint NULL,
    name nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    portalBannerUrl nvarchar(500) NULL,
    iPadBanner bigint NULL,
    createdDate datetime NULL,
    exhibitor bigint NULL,
    banner bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_adbanners_534011718 (modifiedBy,linkType,importCameFrom,infoPage,iPad2BannerUrl,modifiedDate,portalBanner,id,iPadBannerUrl,bannerUrl,_id,createdBy,iPad2Banner,importBatch,name,portalBannerUrl,iPadBanner,createdDate,exhibitor,banner,importKey,_namespace,_dataversion) SELECT modifiedBy,linkType,importCameFrom,infoPage,iPad2BannerUrl,modifiedDate,portalBanner,id,iPadBannerUrl,bannerUrl,_id,createdBy,iPad2Banner,importBatch,name,portalBannerUrl,iPadBanner,createdDate,exhibitor,banner,importKey,_namespace,_dataversion FROM adbanners;

-- Droping the original table and renaming the temporary table

DROP TABLE adbanners;
ALTER TABLE temp_adbanners_534011718 RENAME TO adbanners;

-- Creating table adcampaigns from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_adcampaigns_1655911537
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_adcampaigns_1655911537 (modifiedBy,importCameFrom,modifiedDate,id,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion) SELECT modifiedBy,importCameFrom,modifiedDate,id,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion FROM adcampaigns;

-- Droping the original table and renaming the temporary table

DROP TABLE adcampaigns;
ALTER TABLE temp_adcampaigns_1655911537 RENAME TO adcampaigns;

-- Creating table agendaitems from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_agendaitems_630327709
(
    modifiedBy nvarchar(50) NULL,
    relatedSession bigint NULL,
    importCameFrom nvarchar(500) NULL,
    type nvarchar(500) NULL,
    runningTime_to datetime NULL,
    runningTime_from datetime NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    eventDay nvarchar(50) NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    relatedSubSession bigint NULL,
    relatedMeeting bigint NULL,
    name nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    isDeletable bit NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_agendaitems_630327709 (modifiedBy,relatedSession,importCameFrom,type,runningTime_to,runningTime_from,modifiedDate,visitor,id,eventDay,fullDescription,_id,createdBy,relatedSubSession,relatedMeeting,name,importBatch,isDeletable,createdDate,importKey,_namespace,_dataversion) SELECT modifiedBy,relatedSession,importCameFrom,type,runningTime_to,runningTime_from,modifiedDate,visitor,id,eventDay,fullDescription,_id,createdBy,relatedSubSession,relatedMeeting,name,importBatch,isDeletable,createdDate,importKey,_namespace,_dataversion FROM agendaitems;

-- Droping the original table and renaming the temporary table

DROP TABLE agendaitems;
ALTER TABLE temp_agendaitems_630327709 RENAME TO agendaitems;

-- Creating table articlegroups from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_articlegroups_1752227528
(
    isDashboardFeaturedOnly bit NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(500) PRIMARY KEY ASC NOT NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_articlegroups_1752227528 (isDashboardFeaturedOnly,createdBy,_id,modifiedBy,name,importBatch,importCameFrom,createdDate,modifiedDate,importKey,_namespace,_dataversion) SELECT isDashboardFeaturedOnly,createdBy,_id,modifiedBy,name,importBatch,importCameFrom,createdDate,modifiedDate,importKey,_namespace,_dataversion FROM articlegroups;

-- Droping the original table and renaming the temporary table

DROP TABLE articlegroups;
ALTER TABLE temp_articlegroups_1752227528 RENAME TO articlegroups;

-- Creating table dataversions from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_dataversions_726643700
(
    liveStatus INTEGER NULL,
    scheduledTaskName nvarchar(500) NULL,
    jsonDeletes nvarchar(50) NULL,
    task bigint NULL,
    modifiedBy nvarchar(50) NULL,
    approximateJsonSize INTEGER NULL,
    approximatePlistSize INTEGER NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    timestamp datetime NULL,
    scheduledDate datetime NULL,
    fileFormatVersionJson INTEGER NULL,
    plistUpdates nvarchar(50) NULL,
    scheduledLiveStatus INTEGER NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(500) PRIMARY KEY ASC NOT NULL,
    importBatch nvarchar(500) NULL,
    plistDeletes nvarchar(50) NULL,
    jsonUpdates nvarchar(50) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_dataversions_726643700 (liveStatus,scheduledTaskName,jsonDeletes,modifiedBy,approximateJsonSize,approximatePlistSize,importCameFrom,modifiedDate,timestamp,scheduledDate,fileFormatVersionJson,plistUpdates,scheduledLiveStatus,_id,createdBy,name,importBatch,plistDeletes,jsonUpdates,createdDate,importKey,_namespace,_dataversion,task) SELECT liveStatus,scheduledTaskName,jsonDeletes,modifiedBy,approximateJsonSize,approximatePlistSize,importCameFrom,modifiedDate,timestamp,scheduledDate,fileFormatVersionJson,plistUpdates,scheduledLiveStatus,_id,createdBy,name,importBatch,plistDeletes,jsonUpdates,createdDate,importKey,_namespace,_dataversion,NULL AS task FROM dataversions;

-- Droping the original table and renaming the temporary table

DROP TABLE dataversions;
ALTER TABLE temp_dataversions_726643700 RENAME TO dataversions;

-- Creating table downloadables from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_downloadables_1848543519
(
    modifiedBy nvarchar(50) NULL,
    downloadUrl nvarchar(500) NULL,
    md5Hash nvarchar(500) NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(300) NULL,
    thumbnailUrl nvarchar(500) NULL,
    createdDate datetime NULL,
    mimeType nvarchar(500) NULL,
    fileType nvarchar(500) NULL,
    blobKey nvarchar(50) NULL,
    assosiatedDataFile bigint NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    size INTEGER NULL,
    thumbnail bigint NULL,
    createdBy nvarchar(50) NULL,
    fileName nvarchar(500) NULL,
    exhibitor bigint NULL,
    importKey nvarchar(500) NULL,
    permissionGroup bigint NULL,
    _namespace nvarchar(100) NULL,
    isFavourite BOOLEAN DEFAULT 0,
    hasNote BOOLEAN DEFAULT 0,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_downloadables_1848543519 (modifiedBy,downloadUrl,md5Hash,id,fullDescription,_id,name,importBatch,thumbnailUrl,createdDate,mimeType,fileType,blobKey,assosiatedDataFile,importCameFrom,modifiedDate,size,thumbnail,createdBy,fileName,exhibitor,importKey,permissionGroup,_namespace,isFavourite,hasNote,_dataversion) SELECT modifiedBy,downloadUrl,md5Hash,id,fullDescription,_id,name,importBatch,thumbnailUrl,createdDate,mimeType,fileType,blobKey,assosiatedDataFile,importCameFrom,modifiedDate,size,thumbnail,createdBy,fileName,exhibitor,importKey,permissionGroup,_namespace,isFavourite,hasNote,_dataversion FROM downloadables;

-- Droping the original table and renaming the temporary table

DROP TABLE downloadables;
ALTER TABLE temp_downloadables_1848543519 RENAME TO downloadables;

CREATE TABLE favouriteactivitystreamposts
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    activityStreamPost bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE favouriteactivitystreamposts_relatedTags
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    favouriteactivitystreamposts_id bigint NULL,
    relatedTags bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Creating table favouritedownloadables from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_favouritedownloadables_822959691
(
    groupName nvarchar(500) NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    downloadable bigint NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_favouritedownloadables_822959691 (groupName,modifiedBy,importCameFrom,downloadable,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion) SELECT groupName,modifiedBy,importCameFrom,downloadable,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion FROM favouritedownloadables;

-- Droping the original table and renaming the temporary table

DROP TABLE favouritedownloadables;
ALTER TABLE temp_favouritedownloadables_822959691 RENAME TO favouritedownloadables;

-- Creating table favouriteexhibitors from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_favouriteexhibitors_1944859510
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    exhibitor bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_favouriteexhibitors_1944859510 (modifiedBy,importCameFrom,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,exhibitor,importKey,_namespace,_dataversion) SELECT modifiedBy,importCameFrom,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,exhibitor,importKey,_namespace,_dataversion FROM favouriteexhibitors;

-- Droping the original table and renaming the temporary table

DROP TABLE favouriteexhibitors;
ALTER TABLE temp_favouriteexhibitors_1944859510 RENAME TO favouriteexhibitors;

-- Creating associated indexes from scratch

CREATE INDEX favouriteexhibitors_i7
ON favouriteexhibitors
(
    exhibitor
);

-- Creating table favouritepoi from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_favouritepoi_919275682
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    poi bigint NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_favouritepoi_919275682 (modifiedBy,importCameFrom,modifiedDate,visitor,poi,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion) SELECT modifiedBy,importCameFrom,modifiedDate,visitor,poi,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion FROM favouritepoi;

-- Droping the original table and renaming the temporary table

DROP TABLE favouritepoi;
ALTER TABLE temp_favouritepoi_919275682 RENAME TO favouritepoi;

-- Creating table favouriteproducts from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_favouriteproducts_2041175501
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    product bigint NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_favouriteproducts_2041175501 (modifiedBy,importCameFrom,modifiedDate,visitor,product,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion) SELECT modifiedBy,importCameFrom,modifiedDate,visitor,product,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion FROM favouriteproducts;

-- Droping the original table and renaming the temporary table

DROP TABLE favouriteproducts;
ALTER TABLE temp_favouriteproducts_2041175501 RENAME TO favouriteproducts;

-- Creating table favouritespeakers from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_favouritespeakers_1015591673
(
    speaker bigint NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_favouritespeakers_1015591673 (speaker,modifiedBy,importCameFrom,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion) SELECT speaker,modifiedBy,importCameFrom,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion FROM favouritespeakers;

-- Droping the original table and renaming the temporary table

DROP TABLE favouritespeakers;
ALTER TABLE temp_favouritespeakers_1015591673 RENAME TO favouritespeakers;

-- Creating table favouritevisitors from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_favouritevisitors_2137491492
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    relatedVisitor bigint NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_favouritevisitors_2137491492 (modifiedBy,importCameFrom,relatedVisitor,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion) SELECT modifiedBy,importCameFrom,relatedVisitor,modifiedDate,visitor,id,_id,createdBy,importBatch,createdDate,importKey,_namespace,_dataversion FROM favouritevisitors;

-- Droping the original table and renaming the temporary table

DROP TABLE favouritevisitors;
ALTER TABLE temp_favouritevisitors_2137491492 RENAME TO favouritevisitors;

-- Creating table games from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_games_1111907664
(
    primaryInfoPage bigint NULL,
    modifiedBy nvarchar(50) NULL,
    featured bit NULL,
    importCameFrom nvarchar(500) NULL,
    runningTime_to datetime NULL,
    runningTime_from datetime NULL,
    scoreDisplayStyle INTEGER NULL,
    modifiedDate datetime NULL,
    maxGamePoints INTEGER NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    sponsorCampaign bigint NULL,
    isVisible bit NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    thumbUrl nvarchar(500) NULL,
    thumb bigint NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_games_1111907664 (primaryInfoPage,modifiedBy,featured,importCameFrom,runningTime_to,runningTime_from,scoreDisplayStyle,modifiedDate,maxGamePoints,id,sponsorCampaign,isVisible,_id,createdBy,importBatch,name,thumbUrl,thumb,createdDate,importKey,_namespace,_dataversion) SELECT primaryInfoPage,modifiedBy,featured,importCameFrom,runningTime_to,runningTime_from,scoreDisplayStyle,modifiedDate,maxGamePoints,id,sponsorCampaign,isVisible,_id,createdBy,importBatch,name,thumbUrl,thumb,createdDate,importKey,_namespace,_dataversion FROM games;

-- Droping the original table and renaming the temporary table

DROP TABLE games;
ALTER TABLE temp_games_1111907664 RENAME TO games;

-- Creating table hotspots from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_hotspots_86323836
(
    mapPosition_colour nvarchar(500) NULL,
    mapPosition_vectors nvarchar(500) NULL,
    mapPosition_zIndex int NULL,
    mapPosition_vectorsFormat int NULL,
    mapPosition_textBoundingBox text NULL,
    mapPosition_labelColour nvarchar(500) NULL,
    mapPosition_rotation int NULL,
    mapPosition_map bigint NULL,
    mapPosition_label nvarchar(500) NULL,
    mapPosition_type int NULL,
    mapPosition_version int NULL,
    mapPosition_vectorsBig text NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(100) NULL,
    importBatch nvarchar(500) NULL,
    identifier nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_hotspots_86323836 (mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_textBoundingBox,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,modifiedBy,importCameFrom,modifiedDate,id,_id,createdBy,importBatch,name,identifier,createdDate,importKey,_namespace,_dataversion) SELECT mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_textBoundingBox,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,modifiedBy,importCameFrom,modifiedDate,id,_id,createdBy,importBatch,name,identifier,createdDate,importKey,_namespace,_dataversion FROM hotspots;

-- Droping the original table and renaming the temporary table

DROP TABLE hotspots;
ALTER TABLE temp_hotspots_86323836 RENAME TO hotspots;

-- Creating table inappactions from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_inappactions_1208223655
(
    startDate datetime NULL,
    httpRequestMethod nvarchar(500) NULL,
    modifiedBy nvarchar(50) NULL,
    httpRequestRetry INTEGER NULL,
    httpRequestUrl nvarchar(500) NULL,
    httpRequestBackground bit NULL,
    intentEntityKey nvarchar(500) NULL,
    endDate datetime NULL,
    importCameFrom nvarchar(500) NULL,
    platforms nvarchar(500) NULL,
    repeat INTEGER NULL,
    intentUri nvarchar(500) NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    httpRequestBody nvarchar(500) NULL,
    intentEntityKind nvarchar(500) NULL,
    name nvarchar(100) NULL,
    importBatch nvarchar(500) NULL,
    action nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_inappactions_1208223655 (startDate,modifiedBy,intentEntityKey,endDate,importCameFrom,repeat,intentUri,modifiedDate,id,_id,createdBy,intentEntityKind,importBatch,name,createdDate,importKey,_namespace,_dataversion,httpRequestMethod,httpRequestRetry,httpRequestUrl,httpRequestBackground,platforms,httpRequestBody,action) SELECT startDate,modifiedBy,intentEntityKey,endDate,importCameFrom,repeat,intentUri,modifiedDate,id,_id,createdBy,intentEntityKind,importBatch,name,createdDate,importKey,_namespace,_dataversion,NULL AS httpRequestMethod,NULL AS httpRequestRetry,NULL AS httpRequestUrl,NULL AS httpRequestBackground,NULL AS platforms,NULL AS httpRequestBody,NULL AS action FROM inappactions;

-- Droping the original table and renaming the temporary table

DROP TABLE inappactions;
ALTER TABLE temp_inappactions_1208223655 RENAME TO inappactions;

-- Creating table infopages from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_infopages_182639827
(
    icon nvarchar(500) NULL,
    modifiedBy nvarchar(50) NULL,
    noChildren INTEGER NULL,
    isSecure bit NULL,
    parent bigint NULL,
    importCameFrom nvarchar(500) NULL,
    type nvarchar(500) NULL,
    url nvarchar(500) NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    isRootParent bit NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(100) NULL,
    importBatch nvarchar(500) NULL,
    html text NULL,
    createdDate datetime NULL,
    openEmbedded bit NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_infopages_182639827 (icon,modifiedBy,noChildren,isSecure,parent,importCameFrom,type,url,modifiedDate,id,isRootParent,_id,createdBy,importBatch,name,html,createdDate,openEmbedded,importKey,_namespace,_dataversion) SELECT icon,modifiedBy,noChildren,isSecure,parent,importCameFrom,type,url,modifiedDate,id,isRootParent,_id,createdBy,importBatch,name,html,createdDate,openEmbedded,importKey,_namespace,_dataversion FROM infopages;

-- Droping the original table and renaming the temporary table

DROP TABLE infopages;
ALTER TABLE temp_infopages_182639827 RENAME TO infopages;

-- Creating table locations from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_locations_1304539646
(
    mapPosition_colour nvarchar(500) NULL,
    mapPosition_vectors nvarchar(500) NULL,
    mapPosition_zIndex int NULL,
    mapPosition_vectorsFormat int NULL,
    mapPosition_textBoundingBox text NULL,
    mapPosition_labelColour nvarchar(500) NULL,
    mapPosition_rotation int NULL,
    mapPosition_map bigint NULL,
    mapPosition_label nvarchar(500) NULL,
    mapPosition_type int NULL,
    mapPosition_version int NULL,
    mapPosition_vectorsBig text NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    locationType nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(500) PRIMARY KEY ASC NOT NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_locations_1304539646 (mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_textBoundingBox,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,modifiedBy,importCameFrom,modifiedDate,_id,createdBy,importBatch,name,locationType,createdDate,importKey,_namespace,_dataversion) SELECT mapPosition_colour,mapPosition_vectors,mapPosition_zIndex,mapPosition_vectorsFormat,mapPosition_textBoundingBox,mapPosition_labelColour,mapPosition_rotation,mapPosition_map,mapPosition_label,mapPosition_type,mapPosition_version,mapPosition_vectorsBig,modifiedBy,importCameFrom,modifiedDate,_id,createdBy,importBatch,name,locationType,createdDate,importKey,_namespace,_dataversion FROM locations;

-- Droping the original table and renaming the temporary table

DROP TABLE locations;
ALTER TABLE temp_locations_1304539646 RENAME TO locations;

-- Creating associated indexes from scratch

CREATE INDEX locations_i5
ON locations
(
    name
);

-- Creating table mapfacilities from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_mapfacilities_278955818
(
    logo bigint NULL,
    location nvarchar(50) NULL,
    modifiedBy nvarchar(50) NULL,
    logoUrl nvarchar(500) NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(100) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_mapfacilities_278955818 (logo,location,modifiedBy,logoUrl,importCameFrom,modifiedDate,id,fullDescription,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion) SELECT logo,location,modifiedBy,logoUrl,importCameFrom,modifiedDate,id,fullDescription,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion FROM mapfacilities;

-- Droping the original table and renaming the temporary table

DROP TABLE mapfacilities;
ALTER TABLE temp_mapfacilities_278955818 RENAME TO mapfacilities;

-- Creating table maps from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_maps_1400855637
(
    seqNo bigint NULL,
    imageUrl nvarchar(500) NULL,
    modifiedBy nvarchar(50) NULL,
    type INTEGER NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    colour nvarchar(500) NULL,
    _id nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(200) NULL,
    createdDate datetime NULL,
    icon nvarchar(500) NULL,
    cameraX bigint NULL,
    cameraY bigint NULL,
    cameraZ bigint NULL,
    image bigint NULL,
    importCameFrom nvarchar(500) NULL,
    cameraMinZ bigint NULL,
    modifiedDate datetime NULL,
    emspId nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    rotationOffset bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_maps_1400855637 (cameraX,icon,seqNo,imageUrl,cameraY,modifiedBy,cameraZ,image,importCameFrom,type,cameraMinZ,modifiedDate,colour,id,_id,createdBy,importBatch,name,rotationOffset,createdDate,importKey,_namespace,_dataversion,emspId) SELECT cameraX,icon,seqNo,imageUrl,cameraY,modifiedBy,cameraZ,image,importCameFrom,type,cameraMinZ,modifiedDate,colour,id,_id,createdBy,importBatch,name,rotationOffset,createdDate,importKey,_namespace,_dataversion,NULL AS emspId FROM maps;

-- Droping the original table and renaming the temporary table

DROP TABLE maps;
ALTER TABLE temp_maps_1400855637 RENAME TO maps;

-- Creating table mapzones from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_mapzones_375271809
(
    logo bigint NULL,
    location nvarchar(50) NULL,
    modifiedBy nvarchar(50) NULL,
    logoUrl nvarchar(500) NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(100) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_mapzones_375271809 (logo,location,modifiedBy,logoUrl,importCameFrom,modifiedDate,id,fullDescription,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion) SELECT logo,location,modifiedBy,logoUrl,importCameFrom,modifiedDate,id,fullDescription,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion FROM mapzones;

-- Droping the original table and renaming the temporary table

DROP TABLE mapzones;
ALTER TABLE temp_mapzones_375271809 RENAME TO mapzones;

-- Creating table meetings from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_meetings_1497171628
(
    location nvarchar(500) NULL,
    modifiedBy nvarchar(50) NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    eventDay nvarchar(50) NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(200) NULL,
    isDeletable bit NULL,
    createdDate datetime NULL,
    status INTEGER NULL,
    importCameFrom nvarchar(500) NULL,
    runningTime_to datetime NULL,
    runningTime_from datetime NULL,
    modifiedDate datetime NULL,
    meetingRequestMessage bigint NULL,
    createdBy nvarchar(50) NULL,
    meetingType INTEGER NULL,
    meetingLocation nvarchar(50) NULL,
    exhibitor bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_meetings_1497171628 (location,modifiedBy,id,eventDay,fullDescription,_id,name,importBatch,isDeletable,createdDate,status,importCameFrom,runningTime_to,runningTime_from,modifiedDate,meetingRequestMessage,createdBy,meetingType,meetingLocation,exhibitor,importKey,_namespace,_dataversion) SELECT location,modifiedBy,id,eventDay,fullDescription,_id,name,importBatch,isDeletable,createdDate,status,importCameFrom,runningTime_to,runningTime_from,modifiedDate,meetingRequestMessage,createdBy,meetingType,meetingLocation,exhibitor,importKey,_namespace,_dataversion FROM meetings;

-- Droping the original table and renaming the temporary table

DROP TABLE meetings;
ALTER TABLE temp_meetings_1497171628 RENAME TO meetings;

CREATE TABLE messagecampaigns
(
    associatedTaskSchedule bigint NULL,
    sendInAppMessage bit NULL,
    modifiedBy nvarchar(50) NULL,
    userSegmentation text NULL,
    emailTemplate_body text NULL,
    emailTemplate_replyToTitle nvarchar(500) NULL,
    emailTemplate_replyTo nvarchar(500) NULL,
    emailTemplate_subject nvarchar(500) NULL,
    emailTemplate_rootWidget bigint NULL,
    emailTemplate_myEventCSSOverrideFile bigint NULL,
    messageTemplate_globalMessageTemplate bigint NULL,
    messageTemplate_appMessageTemplate bigint NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    pushNotificationTemplate_body nvarchar(200) NULL,
    _id nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(100) NULL,
    createdDate datetime NULL,
    useMessageTemplate bit NULL,
    campaignType INTEGER NULL,
    inAppMessageTemplate_body text NULL,
    inAppMessageTemplate_author nvarchar(500) NULL,
    inAppMessageTemplate_subject nvarchar(500) NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    sendPushNotification bit NULL,
    createdBy nvarchar(50) NULL,
    sendEmail bit NULL,
    scheduleEnabled bit NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE messagecampaigns_relatedTags
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    messagecampaigns_id bigint NULL,
    relatedTags bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

CREATE TABLE messagecampaigns_taskHistory
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    messagecampaigns_id bigint NULL,
    taskHistory bigint NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Creating table messages from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_messages_471587800
(
    liveStatus INTEGER NULL,
    body text NULL,
    modifiedBy nvarchar(50) NULL,
    subject nvarchar(200) NULL,
    noChildren INTEGER NULL,
    type INTEGER NULL,
    recipient nvarchar(100) NULL,
    scheduledDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    timestamp datetime NULL,
    author nvarchar(100) NULL,
    isRootParent bit NULL,
    scheduledLiveStatus INTEGER NULL,
    _id nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    toVisitor bigint NULL,
    fromExhibitor bigint NULL,
    createdDate datetime NULL,
    scheduledTaskName nvarchar(500) NULL,
    toExhibitor bigint NULL,
    parent bigint NULL,
    importCameFrom nvarchar(500) NULL,
    modifiedDate datetime NULL,
    associatedMeeting bigint NULL,
    createdBy nvarchar(50) NULL,
    fromVisitor bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    isRead BOOLEAN DEFAULT 0,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_messages_471587800 (liveStatus,body,modifiedBy,subject,noChildren,type,recipient,scheduledDate,id,timestamp,author,isRootParent,scheduledLiveStatus,_id,importBatch,toVisitor,fromExhibitor,createdDate,scheduledTaskName,toExhibitor,parent,importCameFrom,associatedMeeting,modifiedDate,createdBy,fromVisitor,importKey,_namespace,isRead,_dataversion) SELECT liveStatus,body,modifiedBy,subject,noChildren,type,recipient,scheduledDate,id,timestamp,author,isRootParent,scheduledLiveStatus,_id,importBatch,toVisitor,fromExhibitor,createdDate,scheduledTaskName,toExhibitor,parent,importCameFrom,associatedMeeting,modifiedDate,createdBy,fromVisitor,importKey,_namespace,isRead,_dataversion FROM messages;

-- Droping the original table and renaming the temporary table

DROP TABLE messages;
ALTER TABLE temp_messages_471587800 RENAME TO messages;

-- Creating table notes from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_notes_1593487619
(
    relatedSpeaker bigint NULL,
    relatedActivityStreamPost bigint NULL,
    modifiedBy nvarchar(50) NULL,
    relatedExhibitor bigint NULL,
    relatedPoi bigint NULL,
    relatedSession bigint NULL,
    importCameFrom nvarchar(500) NULL,
    type nvarchar(500) NULL,
    relatedVisitor bigint NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    relatedDownloadable bigint NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    relatedSubSession bigint NULL,
    importBatch nvarchar(500) NULL,
    relatedProduct bigint NULL,
    createdDate datetime NULL,
    note text NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_notes_1593487619 (relatedSpeaker,modifiedBy,relatedExhibitor,relatedPoi,relatedSession,importCameFrom,type,relatedVisitor,modifiedDate,visitor,relatedDownloadable,id,_id,createdBy,relatedSubSession,importBatch,relatedProduct,createdDate,note,importKey,_namespace,_dataversion,relatedActivityStreamPost) SELECT relatedSpeaker,modifiedBy,relatedExhibitor,relatedPoi,relatedSession,importCameFrom,type,relatedVisitor,modifiedDate,visitor,relatedDownloadable,id,_id,createdBy,relatedSubSession,importBatch,relatedProduct,createdDate,note,importKey,_namespace,_dataversion,NULL AS relatedActivityStreamPost FROM notes;

-- Droping the original table and renaming the temporary table

DROP TABLE notes;
ALTER TABLE temp_notes_1593487619 RENAME TO notes;

-- Creating table permissiongroups from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_permissiongroups_567903791
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    anonymousPermissionSet_canFavourite bit NULL,
    anonymousPermissionSet_canOpen bit NULL,
    anonymousPermissionSet_canView bit NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(300) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    permissionFailureMessage nvarchar(500) NULL,
    everyoneElsePermissionSet_canFavourite bit NULL,
    everyoneElsePermissionSet_canOpen bit NULL,
    everyoneElsePermissionSet_canView bit NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_permissiongroups_567903791 (modifiedBy,importCameFrom,anonymousPermissionSet_canFavourite,anonymousPermissionSet_canOpen,anonymousPermissionSet_canView,modifiedDate,id,_id,createdBy,importBatch,name,createdDate,permissionFailureMessage,everyoneElsePermissionSet_canFavourite,everyoneElsePermissionSet_canOpen,everyoneElsePermissionSet_canView,importKey,_namespace,_dataversion) SELECT modifiedBy,importCameFrom,anonymousPermissionSet_canFavourite,anonymousPermissionSet_canOpen,anonymousPermissionSet_canView,modifiedDate,id,_id,createdBy,importBatch,name,createdDate,permissionFailureMessage,everyoneElsePermissionSet_canFavourite,everyoneElsePermissionSet_canOpen,everyoneElsePermissionSet_canView,importKey,_namespace,_dataversion FROM permissiongroups;

-- Droping the original table and renaming the temporary table

DROP TABLE permissiongroups;
ALTER TABLE temp_permissiongroups_567903791 RENAME TO permissiongroups;

-- Creating table playergames from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_playergames_1689803610
(
    visitorActive bit NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    game bigint NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    totalGamePoints INTEGER NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_playergames_1689803610 (visitorActive,modifiedBy,importCameFrom,game,modifiedDate,visitor,id,_id,createdBy,importBatch,totalGamePoints,createdDate,importKey,_namespace,_dataversion) SELECT visitorActive,modifiedBy,importCameFrom,game,modifiedDate,visitor,id,_id,createdBy,importBatch,totalGamePoints,createdDate,importKey,_namespace,_dataversion FROM playergames;

-- Droping the original table and renaming the temporary table

DROP TABLE playergames;
ALTER TABLE temp_playergames_1689803610 RENAME TO playergames;

-- Creating table poi from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_poi_664219782
(
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    contact_youtubeUrl nvarchar(255) NULL,
    contact_twitter nvarchar(255) NULL,
    contact_linkedIn nvarchar(255) NULL,
    contact_fax nvarchar(100) NULL,
    contact_telephone2 nvarchar(100) NULL,
    contact_email nvarchar(100) NULL,
    contact_facebook nvarchar(255) NULL,
    contact_www nvarchar(255) NULL,
    contact_telephone nvarchar(100) NULL,
    contact_blogUrl nvarchar(255) NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    address_county nvarchar(100) NULL,
    address_postCode nvarchar(45) NULL,
    address_address1 nvarchar(100) NULL,
    address_address2 nvarchar(100) NULL,
    address_town nvarchar(100) NULL,
    address_address3 nvarchar(100) NULL,
    address_country nvarchar(50) NULL,
    name nvarchar(100) NULL,
    importBatch nvarchar(500) NULL,
    thumbUrl nvarchar(500) NULL,
    shareUrl nvarchar(500) NULL,
    thumb bigint NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    isFavourite BOOLEAN DEFAULT 0,
    hasNote BOOLEAN DEFAULT 0,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_poi_664219782 (modifiedBy,importCameFrom,contact_youtubeUrl,contact_twitter,contact_linkedIn,contact_fax,contact_telephone2,contact_email,contact_facebook,contact_www,contact_telephone,contact_blogUrl,modifiedDate,id,fullDescription,_id,createdBy,address_county,address_postCode,address_address1,address_address2,address_town,address_address3,address_country,importBatch,name,thumbUrl,shareUrl,thumb,createdDate,importKey,_namespace,isFavourite,hasNote,_dataversion) SELECT modifiedBy,importCameFrom,contact_youtubeUrl,contact_twitter,contact_linkedIn,contact_fax,contact_telephone2,contact_email,contact_facebook,contact_www,contact_telephone,contact_blogUrl,modifiedDate,id,fullDescription,_id,createdBy,address_county,address_postCode,address_address1,address_address2,address_town,address_address3,address_country,importBatch,name,thumbUrl,shareUrl,thumb,createdDate,importKey,_namespace,isFavourite,hasNote,_dataversion FROM poi;

-- Droping the original table and renaming the temporary table

DROP TABLE poi;
ALTER TABLE temp_poi_664219782 RENAME TO poi;

-- Creating table products from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_products_1786119601
(
    modifiedBy nvarchar(50) NULL,
    contact_youtubeUrl nvarchar(255) NULL,
    contact_twitter nvarchar(255) NULL,
    contact_linkedIn nvarchar(255) NULL,
    contact_fax nvarchar(100) NULL,
    contact_telephone2 nvarchar(100) NULL,
    contact_email nvarchar(100) NULL,
    contact_facebook nvarchar(255) NULL,
    contact_www nvarchar(255) NULL,
    contact_telephone nvarchar(100) NULL,
    contact_blogUrl nvarchar(255) NULL,
    mainImage bigint NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(300) NULL,
    createdDate datetime NULL,
    customField3 nvarchar(100) NULL,
    customField4 nvarchar(100) NULL,
    importCameFrom nvarchar(500) NULL,
    customField1 nvarchar(100) NULL,
    customField2 nvarchar(100) NULL,
    mainImageUrl nvarchar(500) NULL,
    customField5 nvarchar(100) NULL,
    modifiedDate datetime NULL,
    createdBy nvarchar(50) NULL,
    shareUrl nvarchar(500) NULL,
    exhibitor bigint NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    isFavourite BOOLEAN DEFAULT 0,
    hasNote BOOLEAN DEFAULT 0,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_products_1786119601 (modifiedBy,contact_youtubeUrl,contact_twitter,contact_linkedIn,contact_fax,contact_telephone2,contact_email,contact_facebook,contact_www,contact_telephone,contact_blogUrl,mainImage,id,fullDescription,_id,name,importBatch,createdDate,customField3,customField4,importCameFrom,customField1,mainImageUrl,customField2,customField5,modifiedDate,createdBy,shareUrl,exhibitor,importKey,_namespace,isFavourite,hasNote,_dataversion) SELECT modifiedBy,contact_youtubeUrl,contact_twitter,contact_linkedIn,contact_fax,contact_telephone2,contact_email,contact_facebook,contact_www,contact_telephone,contact_blogUrl,mainImage,id,fullDescription,_id,name,importBatch,createdDate,customField3,customField4,importCameFrom,customField1,mainImageUrl,customField2,customField5,modifiedDate,createdBy,shareUrl,exhibitor,importKey,_namespace,isFavourite,hasNote,_dataversion FROM products;

-- Droping the original table and renaming the temporary table

DROP TABLE products;
ALTER TABLE temp_products_1786119601 RENAME TO products;

-- Creating table scheduleitems from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_scheduleitems_760535773
(
    location nvarchar(50) NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    type INTEGER NULL,
    runningTime_to datetime NULL,
    runningTime_from datetime NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    eventDay nvarchar(50) NULL,
    fullDescription text NULL,
    briefDescription nvarchar(500) NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(200) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_scheduleitems_760535773 (location,modifiedBy,importCameFrom,type,runningTime_to,runningTime_from,modifiedDate,id,eventDay,fullDescription,briefDescription,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion) SELECT location,modifiedBy,importCameFrom,type,runningTime_to,runningTime_from,modifiedDate,id,eventDay,fullDescription,briefDescription,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion FROM scheduleitems;

-- Droping the original table and renaming the temporary table

DROP TABLE scheduleitems;
ALTER TABLE temp_scheduleitems_760535773 RENAME TO scheduleitems;

-- Creating table sessions from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_sessions_1882435592
(
    location nvarchar(50) NULL,
    modifiedBy nvarchar(50) NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    feedbackUrl nvarchar(500) NULL,
    eventDay nvarchar(50) NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    briefDescription nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(250) NULL,
    createdDate datetime NULL,
    addToAgendaMessage nvarchar(500) NULL,
    leadChair bigint NULL,
    track nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    runningTime_to datetime NULL,
    runningTime_from datetime NULL,
    modifiedDate datetime NULL,
    createdBy nvarchar(50) NULL,
    shareUrl nvarchar(500) NULL,
    importKey nvarchar(500) NULL,
    permissionGroup bigint NULL,
    _namespace nvarchar(100) NULL,
    isFavourite BOOLEAN DEFAULT 0,
    hasNote BOOLEAN DEFAULT 0,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_sessions_1882435592 (location,modifiedBy,id,feedbackUrl,eventDay,fullDescription,_id,briefDescription,name,importBatch,createdDate,addToAgendaMessage,leadChair,track,importCameFrom,runningTime_to,runningTime_from,modifiedDate,createdBy,shareUrl,importKey,permissionGroup,_namespace,isFavourite,hasNote,_dataversion) SELECT location,modifiedBy,id,feedbackUrl,eventDay,fullDescription,_id,briefDescription,name,importBatch,createdDate,addToAgendaMessage,leadChair,track,importCameFrom,runningTime_to,runningTime_from,modifiedDate,createdBy,shareUrl,importKey,permissionGroup,_namespace,isFavourite,hasNote,_dataversion FROM sessions;

-- Droping the original table and renaming the temporary table

DROP TABLE sessions;
ALTER TABLE temp_sessions_1882435592 RENAME TO sessions;

-- Creating table speakers from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_speakers_856851764
(
    gamePersona_nickname nvarchar(30) NULL,
    modifiedBy nvarchar(50) NULL,
    newPassword nvarchar(500) NULL,
    loginEmailSent bit NULL,
    activeGamePlayer bit NULL,
    password nvarchar(100) NULL,
    userType INTEGER NULL,
    timezone nvarchar(500) NULL,
    username nvarchar(500) NULL,
    mugShotUrl nvarchar(500) NULL,
    fullDescription text NULL,
    lastNames nvarchar(100) NULL,
    createdDate datetime NULL,
    firstNames nvarchar(100) NULL,
    totalPlayerPoints INTEGER NULL,
    companyName nvarchar(100) NULL,
    createdBy nvarchar(50) NULL,
    shareUrl nvarchar(500) NULL,
    importKey nvarchar(500) NULL,
    department nvarchar(100) NULL,
    locale nvarchar(10) NULL,
    mugShot bigint NULL,
    contact_youtubeUrl nvarchar(255) NULL,
    contact_twitter nvarchar(255) NULL,
    contact_linkedIn nvarchar(255) NULL,
    contact_fax nvarchar(100) NULL,
    contact_telephone2 nvarchar(100) NULL,
    contact_email nvarchar(100) NULL,
    contact_facebook nvarchar(255) NULL,
    contact_www nvarchar(255) NULL,
    contact_telephone nvarchar(100) NULL,
    contact_blogUrl nvarchar(255) NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    title nvarchar(20) NULL,
    _id nvarchar(500) NULL,
    briefDescription nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    lastAccessed datetime NULL,
    jobTitle nvarchar(500) NULL,
    enableGamification bit NULL,
    importCameFrom nvarchar(500) NULL,
    visitor bigint NULL,
    modifiedDate datetime NULL,
    address_county nvarchar(100) NULL,
    address_postCode nvarchar(45) NULL,
    address_address1 nvarchar(100) NULL,
    address_address2 nvarchar(100) NULL,
    address_town nvarchar(100) NULL,
    address_address3 nvarchar(100) NULL,
    address_country nvarchar(50) NULL,
    _namespace nvarchar(100) NULL,
    isFavourite BOOLEAN DEFAULT 0,
    hasNote BOOLEAN DEFAULT 0,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_speakers_856851764 (gamePersona_nickname,department,newPassword,modifiedBy,locale,loginEmailSent,mugShot,password,contact_youtubeUrl,contact_twitter,contact_linkedIn,contact_fax,contact_telephone2,contact_email,contact_facebook,contact_www,contact_telephone,contact_blogUrl,activeGamePlayer,userType,id,mugShotUrl,title,username,timezone,fullDescription,briefDescription,_id,importBatch,lastNames,createdDate,jobTitle,firstNames,lastAccessed,totalPlayerPoints,importCameFrom,enableGamification,companyName,visitor,modifiedDate,createdBy,address_county,address_postCode,address_address1,address_address2,address_town,address_address3,address_country,shareUrl,importKey,_namespace,isFavourite,hasNote,_dataversion) SELECT gamePersona_nickname,department,newPassword,modifiedBy,locale,loginEmailSent,mugShot,password,contact_youtubeUrl,contact_twitter,contact_linkedIn,contact_fax,contact_telephone2,contact_email,contact_facebook,contact_www,contact_telephone,contact_blogUrl,activeGamePlayer,userType,id,mugShotUrl,title,username,timezone,fullDescription,briefDescription,_id,importBatch,lastNames,createdDate,jobTitle,firstNames,lastAccessed,totalPlayerPoints,importCameFrom,enableGamification,companyName,visitor,modifiedDate,createdBy,address_county,address_postCode,address_address1,address_address2,address_town,address_address3,address_country,shareUrl,importKey,_namespace,isFavourite,hasNote,_dataversion FROM speakers;

-- Droping the original table and renaming the temporary table

DROP TABLE speakers;
ALTER TABLE temp_speakers_856851764 RENAME TO speakers;

-- Creating table subsessions from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_subsessions_1978751583
(
    modifiedBy nvarchar(50) NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    eventDay nvarchar(50) NULL,
    fullDescription text NULL,
    _id nvarchar(500) NULL,
    briefDescription nvarchar(500) NULL,
    priority INTEGER NULL,
    importBatch nvarchar(500) NULL,
    name nvarchar(250) NULL,
    createdDate datetime NULL,
    addToAgendaMessage nvarchar(500) NULL,
    importCameFrom nvarchar(500) NULL,
    runningTime_to datetime NULL,
    runningTime_from datetime NULL,
    modifiedDate datetime NULL,
    createdBy nvarchar(50) NULL,
    session bigint NULL,
    shareUrl nvarchar(500) NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    isFavourite BOOLEAN DEFAULT 0,
    hasNote BOOLEAN DEFAULT 0,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_subsessions_1978751583 (modifiedBy,id,eventDay,fullDescription,_id,briefDescription,priority,name,importBatch,createdDate,addToAgendaMessage,importCameFrom,runningTime_to,runningTime_from,modifiedDate,createdBy,session,shareUrl,importKey,_namespace,isFavourite,hasNote,_dataversion) SELECT modifiedBy,id,eventDay,fullDescription,_id,briefDescription,priority,name,importBatch,createdDate,addToAgendaMessage,importCameFrom,runningTime_to,runningTime_from,modifiedDate,createdBy,session,shareUrl,importKey,_namespace,isFavourite,hasNote,_dataversion FROM subsessions;

-- Droping the original table and renaming the temporary table

DROP TABLE subsessions;
ALTER TABLE temp_subsessions_1978751583 RENAME TO subsessions;

-- Creating table tagsv2 from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_tagsv2_953167755
(
    modifiedBy nvarchar(50) NULL,
    noChildren INTEGER NULL,
    parent bigint NULL,
    label nvarchar(500) NULL,
    importCameFrom nvarchar(500) NULL,
    isArchived bit NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    sponsorCampaign bigint NULL,
    entityBitMask INTEGER NULL,
    isRootParent bit NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    importBatch nvarchar(500) NULL,
    path nvarchar(500) NULL,
    archivedDate datetime NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_tagsv2_953167755 (modifiedBy,noChildren,parent,importCameFrom,label,isArchived,modifiedDate,id,sponsorCampaign,isRootParent,_id,createdBy,importBatch,path,archivedDate,createdDate,importKey,_namespace,_dataversion,entityBitMask) SELECT modifiedBy,noChildren,parent,importCameFrom,label,isArchived,modifiedDate,id,sponsorCampaign,isRootParent,_id,createdBy,importBatch,path,archivedDate,createdDate,importKey,_namespace,_dataversion,NULL AS entityBitMask FROM tagsv2;

-- Droping the original table and renaming the temporary table

DROP TABLE tagsv2;
ALTER TABLE temp_tagsv2_953167755 RENAME TO tagsv2;

CREATE TABLE tagsv2_dirtyEntities
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    tagsv2_id bigint NULL,
    dirtyEntities nvarchar(500) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Creating table trophies from scratch (simple ALTER TABLE is not enough)

CREATE TABLE temp_trophies_2075067574
(
    primaryInfoPage bigint NULL,
    icon nvarchar(500) NULL,
    maxTrophyPoints INTEGER NULL,
    modifiedBy nvarchar(50) NULL,
    importCameFrom nvarchar(500) NULL,
    game bigint NULL,
    runningTime_to datetime NULL,
    runningTime_from datetime NULL,
    modifiedDate datetime NULL,
    id INTEGER PRIMARY KEY ASC NOT NULL,
    sponsorCampaign bigint NULL,
    isVisible bit NULL,
    _id nvarchar(500) NULL,
    createdBy nvarchar(50) NULL,
    name nvarchar(500) NULL,
    importBatch nvarchar(500) NULL,
    createdDate datetime NULL,
    importKey nvarchar(500) NULL,
    _namespace nvarchar(100) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

-- Copying rows from original table to the new table

INSERT INTO temp_trophies_2075067574 (primaryInfoPage,icon,maxTrophyPoints,modifiedBy,importCameFrom,game,runningTime_to,runningTime_from,modifiedDate,id,sponsorCampaign,isVisible,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion) SELECT primaryInfoPage,icon,maxTrophyPoints,modifiedBy,importCameFrom,game,runningTime_to,runningTime_from,modifiedDate,id,sponsorCampaign,isVisible,_id,createdBy,importBatch,name,createdDate,importKey,_namespace,_dataversion FROM trophies;

-- Droping the original table and renaming the temporary table

DROP TABLE trophies;
ALTER TABLE temp_trophies_2075067574 RENAME TO trophies;

CREATE TABLE visitors_secondaryVisitorGroups
(
    seqNo bigint NOT NULL,
    _namespace nvarchar(100),
    visitors_id bigint NULL,
    secondaryVisitorGroups nvarchar(50) NULL,
    _dataversion NVARCHAR(100) DEFAULT (NULL)
);

COMMIT TRANSACTION;
